name: Github Pages Deploy

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install, build
        run: npm install && npm install -S serve && npm run build

      # - name: serve app
      #   run: serve -s build
      - name: see package
        run: cat package.json

      - name: Install Playwright
        run: npx playwright install-deps && npx playwright install

      # - name: Run application
      #   run: serve -s build

      - name: Run tests
        run: npx playwright test --browser=all

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build
