name: Github Pages Deploy

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install, build
        run: npm install && npm install -g serve wait-on && npm run build

      - name: see version
        run: serve -v

      - name: serve app
        run: serve -s build & npx wait-on http://localhost:5000

      - name: test
        run: ls

  test:
    runs-on: ubuntu-latest
    # needs: build
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Install Playwright
        run: npx playwright install-deps && npx playwright install
      # - name: Run application
      #   run: serve -s build

      - name: Run tests
        run: sleep 45 && npx playwright test --browser=all

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build
